# version: "3.7"
services:
  app:
    build:
      args:
        user: nursultan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp_container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - myapp_network

  db:
    image: mysql/mysql-server:5.7
    container_name: myapp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - myapp_network


  nginx:
    image: nginx:alpine
    container_name: myapp_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: bridge
